### PR TITLE
port 3.x ~

### PR DESCRIPTION
**Pull request by AkagiShiroe**
here you go~ without code reformatting @mauzel

### CODE REVIEW

**Comment by mauzel** [comment]
Thanks. Since I don't have any unit or integration tests 😭  I will manually test this pull request later tonight to make sure it works for me. If it works, then I will merge this PR.

**Comment by AkagiShiroe** [comment]
well, i allready test it.. working fine correctly here (3.6 compiled via pyinstaller)
the funny part are.. this cache can also be used in android nee~
image

**Comment by mauzel** [comment]
Thanks for showing that it works. I believe you, I just want to make sure I setup some Python 3 virtualenv stuff and update the README before I accept the PR.

Some of my friends want to use this software but they aren't good at computers so on top of the Python 3.x port, I want to add some instructions to the README later tonight.

**Comment by mauzel** [comment]
@AkagiShiroe It looks like you are missing the changes for gbfproxy/handlers.py, could you please include the changes for that file as well?

**Comment by AkagiShiroe** [comment]
@mauzel ah now you mention it, i skip this one, sorry just forget to modify fork

**Comment by mauzel** [comment]
No problem, I will check again later tonight, but it should probably be good now.

**Pull request merged**
